CREATE TABLE IF NOT EXISTS units_measurement (
    id   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name character varying(255) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS types_parameters (
    id      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name    character varying(255) NOT NULL UNIQUE,
    unit_id integer NOT NULL
);

INSERT INTO units_measurement (id, name) VALUES
    (1, 'Метры'),
    (2, 'мм. рт. ст.'),
    (3, 'Цельсий'),
    (4, 'Градусы'),
    (5, 'м/с')
ON CONFLICT (id) DO NOTHING;

INSERT INTO types_parameters (id, name, unit_id) VALUES
    (1, 'Высота метеопоста', 1),
    (2, 'Температура', 3),
    (3, 'Давление', 2),
    (4, 'Направление ветра', 4),
    (5, 'Скорость ветра', 5),
    (6, 'Дальность сноса пуль', 1)
ON CONFLICT (id) DO NOTHING;

SELECT setval('units_measurement_id_seq', (SELECT COALESCE(MAX(id), 1) FROM units_measurement));
SELECT setval('types_parameters_id_seq', (SELECT COALESCE(MAX(id), 1) FROM types_parameters));

ALTER TABLE ranks ALTER COLUMN name SET DATA TYPE character varying(255);
ALTER TABLE users ALTER COLUMN name SET DATA TYPE character varying(255);
ALTER TABLE equipments ALTER COLUMN name SET DATA TYPE character varying(255);

ALTER TABLE parameters ALTER COLUMN station_height DROP NOT NULL;
ALTER TABLE parameters ALTER COLUMN temperature DROP NOT NULL;
ALTER TABLE parameters ALTER COLUMN pressure DROP NOT NULL;

ALTER TABLE parameters ADD COLUMN IF NOT EXISTS log_id integer;
ALTER TABLE parameters ADD COLUMN IF NOT EXISTS parametr_id integer;
ALTER TABLE parameters ADD COLUMN IF NOT EXISTS units_id integer;
ALTER TABLE parameters ADD COLUMN IF NOT EXISTS parametr_value decimal(10,2);

INSERT INTO parameters (log_id, parametr_id, units_id, parametr_value)
SELECT l.id, 1, 1, CAST(p.station_height AS decimal(10,2))
FROM parameters p
INNER JOIN logs l ON l.parametrs_id = p.id
WHERE p.station_height IS NOT NULL;

INSERT INTO parameters (log_id, parametr_id, units_id, parametr_value)
SELECT l.id, 2, 3, CAST(p.temperature AS decimal(10,2))
FROM parameters p
INNER JOIN logs l ON l.parametrs_id = p.id
WHERE p.temperature IS NOT NULL;

INSERT INTO parameters (log_id, parametr_id, units_id, parametr_value)
SELECT l.id, 3, 2, CAST(p.pressure AS decimal(10,2))
FROM parameters p
INNER JOIN logs l ON l.parametrs_id = p.id
WHERE p.pressure IS NOT NULL;

INSERT INTO parameters (log_id, parametr_id, units_id, parametr_value)
SELECT l.id, 4, 4, CAST(p.wind_direction AS decimal(10,2))
FROM parameters p
INNER JOIN logs l ON l.parametrs_id = p.id
WHERE p.wind_direction IS NOT NULL;

INSERT INTO parameters (log_id, parametr_id, units_id, parametr_value)
SELECT l.id, 5, 5, CAST(p.wind_speed AS decimal(10,2))
FROM parameters p
INNER JOIN logs l ON l.parametrs_id = p.id
WHERE p.wind_speed IS NOT NULL;

INSERT INTO parameters (log_id, parametr_id, units_id, parametr_value)
SELECT l.id, 6, 1, CAST(p.bullet_drift AS decimal(10,2))
FROM parameters p
INNER JOIN logs l ON l.parametrs_id = p.id
WHERE p.bullet_drift IS NOT NULL;

DELETE FROM parameters WHERE log_id IS NULL;

ALTER TABLE parameters DROP COLUMN IF EXISTS station_height;
ALTER TABLE parameters DROP COLUMN IF EXISTS temperature;
ALTER TABLE parameters DROP COLUMN IF EXISTS pressure;
ALTER TABLE parameters DROP COLUMN IF EXISTS wind_direction;
ALTER TABLE parameters DROP COLUMN IF EXISTS wind_speed;
ALTER TABLE parameters DROP COLUMN IF EXISTS bullet_drift;

ALTER TABLE logs DROP COLUMN IF EXISTS parametrs_id;

ALTER TABLE parameters ALTER COLUMN log_id SET NOT NULL;
ALTER TABLE parameters ALTER COLUMN parametr_id SET NOT NULL;
ALTER TABLE parameters ALTER COLUMN units_id SET NOT NULL;
ALTER TABLE parameters ALTER COLUMN parametr_value SET NOT NULL;

SELECT logs.date, logs.id, users.name, types_parameters.name, units_measurement.name, parameters.parametr_value
FROM types_parameters, units_measurement, logs, parameters, equipments, users, ranks
WHERE
        parameters.parametr_id = types_parameters.id
    AND parameters.units_id = units_measurement.id
    AND users.id = logs.user_id
    AND users.rank_id = ranks.id
    AND equipments.id = logs.equipment_id
    AND parameters.log_id = logs.id
ORDER BY logs.id;