CREATE TABLE IF NOT EXISTS Logs(
	id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	user_id int NOT NULL,
	parametrs_id int NOT NULL,
	equipment_id int NOT NULL,
	date timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Users(
	id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name text,
	rank_id int
);

CREATE TABLE IF NOT EXISTS Ranks(
	id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name text UNIQUE
);

CREATE TABLE IF NOT EXISTS Parameters(
	id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	station_height int NOT NULL,
	temperature float CHECK(temperature >= -58 AND temperature <= 58) NOT NULL,
	pressure int CHECK(pressure >= 500 and pressure <= 900) NOT NULL,
	wind_direction int CHECK(wind_direction >= 0 AND wind_direction <= 59),
	wind_speed int CHECK(wind_speed >= 0 AND wind_speed <= 15) DEFAULT NULL,
	bullet_drift int CHECK(bullet_drift >= 0 AND bullet_drift <= 150) DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS Equipments(
	id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name text UNIQUE
);

INSERT INTO Logs(id, user_id, parametrs_id, equipment_id) VALUES
	(1,4,2,2),
	(2,3,4,1),
	(3,2,1,1),
	(4,1,4,2)
	ON CONFLICT(id) DO NOTHING;

INSERT INTO Users (id, name, rank_id) VALUES
	(1, 'Иванов Сергей Николаевич', 1),
	(2, 'Петров Алексей Владимирович', 3),
	(3, 'Сидоров Роман Игоревич', 7),
	(4, 'Смирнова Анна Александровна', 10),
	(5, 'Кузнецов Дмитрий Сергеевич', 14),
	(6, 'Попов Михаил Юрьевич', 2),
	(7, 'Васильев Андрей Олегович', 5),
	(8, 'Соколов Артем Андреевич', 11),
	(9, 'Михайлов Александр Викторович', 16),
	(10, 'Новиков Илья Дмитриевич', 4),
	(11, 'Федоров Денис Евгеньевич', 8),
	(12, 'Морозов Никита Владимирович', 12)
	ON CONFLICT(id) DO NOTHING;

INSERT INTO Ranks(name) VALUES
	('Рядовой'),
	('Ефрейтор'),
	('Младший сержант'),
	('Сержант'),
	('Старший сержант '),
	('Старшина'),
	('Прапорщик'),
	('Старший прапорщик'),
	('Младший лейтенант'),
	('Лейтенант'),
	('Старший лейтенант'),
	('Капитан')
	ON CONFLICT(name) DO NOTHING;

INSERT INTO Parameters(id, station_height, temperature, pressure, wind_direction, wind_speed) VALUES 
	(1, 150, 15.4, 750, 11, 5),
	(2, 340, -10.2, 720, 0, 12)
	ON CONFLICT(id) DO NOTHING;

INSERT INTO Parameters(id, station_height, temperature, pressure, wind_direction, bullet_drift) VALUES 
	(3, 1200, -45.5, 610, 58, 115),
	(4, 510, 5.0, 742, 15, 10)
	ON CONFLICT(id) DO NOTHING;

INSERT INTO Equipments(name) VALUES
	('ДМК'),
	('ВР')
	ON CONFLICT(name) DO NOTHING;

SELECT setval('logs_id_seq', (SELECT MAX(id) FROM Logs));
SELECT setval('users_id_seq', (SELECT MAX(id) FROM Users));
SELECT setval('ranks_id_seq', (SELECT MAX(id) FROM Ranks));
SELECT setval('parameters_id_seq', (SELECT MAX(id) FROM Parameters));
SELECT setval('equipments_id_seq', (SELECT MAX(id) FROM Equipments));

SELECT *
FROM Logs
INNER JOIN Users ON Users.id = Logs.user_id
INNER JOIN Ranks ON Ranks.id = users.rank_id
INNER JOIN Parameters ON Parameters.id = logs.parametrs_id
INNER JOIN Equipments ON Equipments.id = logs.equipment_id;